### ISSUE TITLE
api 404

### ISSUE THREAD

**Issue by AdelEddarai** [ucsd-creativitylab/graphologue#5]
i have add api key in my .env but i get this error in web console : 

"openAI.ts:109 
        POST https://api.openai.com/v1/chat/completions 404 (Not Found)"

**Comment by peilingjiang** [comment]
Hi, did you put it as `REACT_APP_OPENAI_API_KEY=` in your .env file? The key is used at https://github.com/ucsd-creativitylab/graphologue/blob/efb997c550a0cb8133c3dcaf8a3766f6449de385/src/utils/openAI.ts#L67 and I suggest printing the variable out here (i.e. `console.log(process.env.REACT_APP_OPENAI_API_KEY)`) to see if the API key is loaded successfully.
